CREATE TABLE PUBLIC.USERS (ID integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
																												NAME VARCHAR(50) NOT NULL,
																												LASTNAME VARCHAR(80) NOT NULL,
																												EMAIL VARCHAR(80) UNIQUE NOT NULL,
																												PASSWORD VARCHAR(100) NOT NULL,
																												AVATAR VARCHAR(50));


CREATE TABLE PUBLIC.CATEGORIES (ID integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
																																	NAME VARCHAR(50) UNIQUE NOT NULL);


CREATE TABLE PUBLIC.ARTICLES
	(ID integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
			TITLE VARCHAR(150) NOT NULL,
			CREATEDDATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
			IMAGE VARCHAR(50) NOT NULL,
			ANNOUNCE VARCHAR(250) NOT NULL,
			FULLTEXT text NOT NULL,
			USERID integer NOT NULL,
		FOREIGN KEY (USERID) REFERENCES USERS(ID) ON DELETE CASCADE ON UPDATE CASCADE);


CREATE TABLE PUBLIC.ARTICLE_CATEGORIES
	(ARTICLEID integer NOT NULL,
			CATEGORYID integer NOT NULL,
			PRIMARY KEY (ARTICLEID,
																	CATEGORYID),
		FOREIGN KEY (ARTICLEID) REFERENCES ARTICLES(ID) ON DELETE CASCADE ON UPDATE CASCADE,
		FOREIGN KEY (CATEGORYID) REFERENCES CATEGORIES(ID) ON DELETE CASCADE ON UPDATE CASCADE);


CREATE TABLE PUBLIC.COMMENTS
	(ID integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
			ARTICLEID integer NOT NULL,
			USERID integer NOT NULL,
			CREATEDDATE TIMESTAMP NOT NULL, text text NOT NULL,
		FOREIGN KEY (ARTICLEID) REFERENCES ARTICLES(ID) ON DELETE CASCADE ON UPDATE CASCADE,
		FOREIGN KEY (USERID) REFERENCES USERS(ID) ON DELETE CASCADE ON UPDATE CASCADE);


CREATE INDEX ON ARTICLES(TITLE);
